### ISSUE TITLE
HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by LingamYoni** [devapromix/lizardry#1]
После успешной регистрации при нажатии на кнопку вход:
![2021-09-17_102538](https://user-images.githubusercontent.com/40486018/133742354-8f94dc34-1464-4113-85a0-963c9be63bc7.png)
и далее
[Window Title]
Lizardry

[Content]
Ошибка авторизации!

[OK]

**Comment by devapromix** [comment]
Спасибо!

**Comment by devapromix** [comment]
Пофиксил проблему.

**Comment by LingamYoni** [comment]
Да, теперь первой ошибки нет, но все еще осталась вторая :)
**Ошибка авторизации!**

**Comment by devapromix** [comment]
Спасибо :)

**Comment by devapromix** [comment]
Пофиксил. Нужно обновить клиент до 0.0.3.
