### ISSUE TITLE
Не обновляются подсказки для предметов

### ISSUE THREAD

**Issue by devapromix** [devapromix/lizardry#103]
А вот баг
![изображение](https://user-images.githubusercontent.com/40486018/202154274-12c6364c-965e-41d9-82d3-3a526f280ed0.png)
После юзанья свитка благословения прямо в таверне через инвентарь, при возврате из него пища приобрела свойства свитка ))

_Originally posted by @LingamYoni in https://github.com/devapromix/lizardry/issues/99#issuecomment-1316751655_

**Comment by devapromix** [comment]
Этот баг больше не повторялся?

**Comment by LingamYoni** [comment]
Сейчас повторил. При возврате из инвентаря жареная телятина имела описание от свитка. Если кликнуть по ней, то описание менялось на корректное.

**Comment by devapromix** [comment]
Исправлено
