### ISSUE TITLE
Случайные локации с сундуками разных уровней -- простые, сложные и уникальные

### ISSUE THREAD

**Issue by devapromix** [devapromix/lizardry#109]
Случайная локация с разными закрытыми сундуками. Для открытия нужно иметь в инвентаре ключи. Простой сундук открыть -- использовать 1 ключ. Уникальный -- три ключа.

**Comment by phomm** [comment]
Why did you put "good first issue" label ? :)

**Comment by devapromix** [comment]
А що не так?
