### ISSUE TITLE
0.0.9

### ISSUE THREAD

**Issue by LingamYoni** [devapromix/lizardry#11]
Фигассе ребаланс произошел:
```
Вы вступаете в схватку с Костяной Лорд.
Вы бросаетесь в атаку!
--------------------------------------------------------
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 3 HP.
Костяной Лорд ранит вас на 2 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 1 HP.
Вы промахиваетесь по Костяной Лорд.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 3 HP.
Костяной Лорд промахивается по вам.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд промахивается по вам.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 3 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 3 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд промахивается по вам.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 3 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 2 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 4 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 2 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 2 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 2 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 2 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд промахивается по вам.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд промахивается по вам.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 3 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 3 HP.
Вы раните Костяной Лорд на 2 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 3 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 2 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 3 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 2 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 4 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд промахивается по вам.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 1 HP.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд промахивается по вам.
Вы промахиваетесь по Костяной Лорд.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 2 HP.
Вы раните Костяной Лорд на 3 HP.
Вы раните Костяной Лорд на 3 HP.
Костяной Лорд ранит вас на 3 HP.
Костяной Лорд ранит вас на 1 HP.
Вы раните Костяной Лорд на 2 HP.
Вы раните Костяной Лорд на 2 HP.
Костяной Лорд ранит вас на 1 HP.
Костяной Лорд наносит удар на 1 HP и убивает вас.
--------------------------------------------------------
Вы потеряли пятую часть опыта и седьмую часть золота.
--------------------------------------------------------
Всего раундов: 47
Сумма урона: 108 (Shock) / 75 (Костяной Лорд)
Промахи: 10 (Shock) / 7 (Костяной Лорд)
```
Раньше в этой локе мобы ложились пачками, даже 24-го уровня. А теперь ложусь я :)))

**Comment by LingamYoni** [comment]
По кнопке "Обновление" не происходит само обновление, хотя в хинте написано что можно проверить (это работает) и обновить (а это - нет).

**Comment by LingamYoni** [comment]
Еще. В Морхольде торговцы продают вещи первого города (как его там?), т.е. до 12 уровня, а было до 24 уровня.

**Comment by LingamYoni** [comment]
Хм. Выбил меч (такой же, как у меня), пытаюсь его "взять", а мне пишут "Вы бросаете свой старый Кожаный Панцирь и берете в руки новый Кожаный Панцирь" - налицо баг.
И, кстати, дать бы возможность копировать текст сообщений, а то утомительно переписывать :)

**Comment by LingamYoni** [comment]
И иконку бы приложению задать, а то дефолтная делфовская - некрасиво ;)

**Comment by devapromix** [comment]
Спасибо за багрепорт. Принял.

**Comment by devapromix** [comment]
Насчет обновления: планируется целая страница на манер страницы регистрации. В будущем :)

**Comment by devapromix** [comment]
Уменьшено здоровье и урон у мобов. Обновил сервер.

**Comment by LingamYoni** [comment]
Не сильно ли уменьшено? Теперь 22й почти не пробивает моего 23 уровня :) Да и 24е легко теперь складываются.

**Comment by devapromix** [comment]
Добавил немножечко урона :) Как теперь?

**Comment by devapromix** [comment]
Там надо смотреть на их урон и на здоровье. Встречаются более колючие или более здоровые :) Их можно победить. Совсем плохо будет, если колючие и здоровые :) Все это с ребалансом начато из -за того, что скоро будут добавлены элитные монстры :)

**Comment by LingamYoni** [comment]
Ну, теперь жестко. По-моему, еще жестче, чем было :)) 23й Лорд выносит моего 23го как салагу :)

**Comment by LingamYoni** [comment]
Выбил "гарантовый эликсир горностая" - и как его юзать?

**Comment by devapromix** [comment]
Обновил сервер. Жмем на имя персонажа (там уже кнопка), открывается инвентарь, двойной щелчек как при покупке в магазине.

**Comment by devapromix** [comment]
2 после названия предмета -- это уровень предмета :) Если количество -- в конце после чила будет х.

**Comment by devapromix** [comment]
Насчет подсказки - да. Чет такое придумаю в след. версии.

**Comment by LingamYoni** [comment]
Ок)) Ладно, творческой ночи, а я спать ;)

**Comment by devapromix** [comment]
Спасибо за тестирование :)

**Comment by LingamYoni** [comment]
Не засек когда пропало, но точно помню, что выбивал зелье и не тратил его. А захожу в инвентарь, а там пусто :(
И еще, у перса моего 80 хп на 24 уровне, это нормально? У мобов чуть не в 2 раза выше))
Я еще до введения оружия вкладывал уровни в урон, а не в тело. А потом вдруг раз! и оружие заместило вкачанный урон. А тело-то ведь как было, так и осталось непрокачанное (если бы я весь опыт в тело вкладывал)...

**Comment by devapromix** [comment]
Да, такое может случаться :) Вот вчера во время тестирования у меня пропал целый инвентарь с кучей зелий :) Пока все отлажу, пока понахожу все ошибки. Вообщем это надо пережить :)
Насчет второго, я думаю как решить эту проблему. Похоже надо все переделать и сделать так, чтобы с каждым уровнем у перса автоматом росло HP, MP и что-то там еще :) Ведь у монстров так, за ними в плане баланса не угнаться. Ну и насчет третьего -- будет добавлена лавка или гильдия с NPC, где можно будет сбросить все очки до 1-го уровня (но не сам уровень), и перекачать их по новому в новых гильдиях. Формула уже намечена и там не потеряется ни один уровень. Возможно надо будет выполнить для этого маленький квест. Время покажет.

**Comment by LingamYoni** [comment]
Переживем, не вопрос :) В общем, жду новых релизов с новыми и исправленными багами, куда ж без них :))

**Comment by devapromix** [comment]
Вернул эликсир на место :) Почему так происходит так с ходу не понял, буду думать дальше. Новая версия не за горами :)

**Comment by devapromix** [comment]
Уже доступна новая версия 0.1. Можно тестировать :)
