### ISSUE TITLE
0.1.3

### ISSUE THREAD

**Issue by LingamYoni** [devapromix/lizardry#15]
После нескольких боев, при очередном нажатии на автобой AV "read address 00000000" и затем такой лог:
![изображение](https://user-images.githubusercontent.com/40486018/148641960-4dcee2af-eb95-4c4f-8668-d7e4ea642af1.png)

**Comment by devapromix** [comment]
Сдается мне это была Адская Гончая :) Спасибо! Буду искать причину.

**Comment by LingamYoni** [comment]
Опечатки:
![изображение](https://user-images.githubusercontent.com/40486018/149881149-5192b4df-e447-4145-8f5a-5641c28dddbe.png)
![изображение](https://user-images.githubusercontent.com/40486018/149881173-8678e742-b8e1-451f-8cf9-7cf278694cc9.png)
![изображение](https://user-images.githubusercontent.com/40486018/149881197-9998bad4-cd10-4bf0-8cd8-5257ed3ea7a7.png)

**Comment by LingamYoni** [comment]
Что-то апдейты кончились)
Вопрос: по-моему, уже 4 раза за все время выпадал ценный лут. И всегда это было оружие. Броня не дропается?

**Comment by devapromix** [comment]
Привет :) Жесткий реал :) Продолжу как освобожусь. Я думаю должна выпадать, но гляну как там в коде.

**Comment by LingamYoni** [comment]
Главное вовремя пожаловаться)) сегодня выпала таки бронька)

**Comment by LingamYoni** [comment]
Кстати, вопрос. Всегда дропается то же самое оружие/броня, что надето на персе. Это спецом так сделано? Получается, что нет смысла ждать дропа **лучшего** предмета, а всегда надо его покупать. И такой дроп просто продается ради денег, надеть его нельзя, апгрейднув героя((

**Comment by LingamYoni** [comment]
Эта... приплыл я в Эндалион, а там и биться-то не с кем. Чем теперь досуг занимать на работе? :))

**Comment by devapromix** [comment]
Ну там с меньшим шансом может выпасть бронь/меч получше.

Уже? Я помню там регион не заселен еще. Постараюсь побыстрей наполнить :)
