### ISSUE TITLE
Проект - фсё?

### ISSUE THREAD

**Issue by LingamYoni** [devapromix/lizardry#16]
сабж

**Comment by LingamYoni** [comment]
Привет, ну интерес-то есть - на работе скучно бывает))) Однако, если это игра только для меня одного)), то есть ли смысл продолжать?) А так - да, давно жду обнов, а сегодня запустил, а там - HTTP/1.1 404 Not Found, отсюда и вопрос.

**Comment by LingamYoni** [comment]
Вижу - процесс помаленьку идет) Но вот мой перс прибыл в Эндалион, а он остается пустым уже месяцы, некого там гнобить)) Просьба населить его гадами)

**Comment by devapromix** [comment]
Привет)) Вот собираюсь с силами. Скоро уже...

**Comment by devapromix** [comment]
Новая версия. Можно тестировать)

**Comment by LingamYoni** [comment]
Ну, вроде работает :)
С чатом только непонятка - с кем чатиться-то?) И это норм, что только одно слово можно отправить? Еслид два и более, то в ответ окно с ошибкой "400 бэд реквест"

**Comment by devapromix** [comment]
Мдя)) Буду смотреть что там с чатом)

**Comment by phomm** [comment]
@LingamYoni зачётный ник :3

**Comment by LingamYoni** [comment]
Странная математика:
![2022-07-29_084226](https://user-images.githubusercontent.com/40486018/181691730-c8bd2a08-4607-4a22-a7fc-0b1054c6e901.jpg)

**Comment by devapromix** [comment]
Спасибо, гляну чего там.

**Comment by devapromix** [comment]
По коду вроде все гладко. Мог ли перс перед боем иметь здоровья 260/280?

**Comment by LingamYoni** [comment]
Oops, my bad! ( Ну конечно же, перс был не с полным здоровьем!) Все ок, удалил свой пост.

**Comment by LingamYoni** [comment]
Что-то сегодня пошло не так... при запуске сначала
![1](https://user-images.githubusercontent.com/40486018/182223420-a838491d-9644-4776-b353-175e52c45bf0.jpg)
потом
![2](https://user-images.githubusercontent.com/40486018/182223438-b1ac8e87-7dd8-42c7-8a45-4b5fe79ff1e0.jpg)
далее выбор учетной записи с пустым логом последних событий. После кнопки ВХОД сновый 1й скрин, потом оно же с текстом "Ошибка авторизации" и висим на этапе "Подтверждение авторизации..."

**Comment by devapromix** [comment]
Принял. Погляжу что там с сервером.

**Comment by LingamYoni** [comment]
Все еще не фунциклирует(

**Comment by devapromix** [comment]
Привет. Меняю хостинг. Еще надо подождать.

**Comment by devapromix** [comment]
Думаю эту проблему мы решили успешно :)
