### ISSUE TITLE
Баги v.0.0.3

### ISSUE THREAD

**Issue by LingamYoni** [devapromix/lizardry#2]
1. Иногда в бою выбранный медведь после первого автохода превращается в волка, и наоборот. Вот подстава!))
2. Жмешь костер, отдыхаешь (видно восполнение хп), затем переходишь в бой, а там снова подстава - хп становится как до отдыха, и тебя быстро убивают, если не проконтролировал, что **реально** отдохнул.
3. Как так, см. скриншот.
![2021-10-13_143824](https://user-images.githubusercontent.com/40486018/137125886-046cf58d-ba1f-4a76-8787-b07e2754985d.jpg)

4. Где "Огромный фэнтезийный мир, наполненный разнообразными тайными местами, подземельями и руинами;"? Пока вижу только один темный лес))

**Comment by LingamYoni** [comment]
Или вот еще:
![2021-10-13_144853](https://user-images.githubusercontent.com/40486018/137126998-0f86389b-2617-4636-8343-99e7f08936ab.jpg)
Один мой удар на 4 сваншотил медведя 25/25. Жаль такое нечасто бывает)))

**Comment by devapromix** [comment]
Спасибо :)

**Comment by devapromix** [comment]
Насчет п. 4 --в процессе))

**Comment by LingamYoni** [comment]
И оружия, брони еще бы :) Вообще магазинчик бы еще, а то деньги даже некуда тратить :)

**Comment by devapromix** [comment]
Ну да. И магазинчик добавим позднее :)

**Comment by devapromix** [comment]
Щас пофиксю кое что и через 2-3 часика думаю))

**Comment by devapromix** [comment]
Еще часик :)

**Comment by LingamYoni** [comment]
Блин, баг с отдыхом реально выбесивает: жмешь костер, хп восполнилось, жмешь "Затушить костер" - а хп опять как до отдыха. И так по несколько раз надо сделать, чтобы рельно отдохнуть.
И в пещере появляются волки с пауками хотя выбираешь гоблина, а в лесу наоборот гоблины вмсето пауков/волков/медведей. 
Надо это пофиксить, очень раздражает...
