### ISSUE TITLE
Локация-событие "Ограбление"

### ISSUE THREAD

**Issue by devapromix** [devapromix/lizardry#28]
Добавить возможность ограбить игрока. Количество золота зависит от региона.

**Comment by LingamYoni** [comment]
Ничего не понятно, но очень интересно)) Как/где бужет происходить ограбление? Откуда будет брать золото грабитель, если с собой его нет (все в банке храню - это же надежно?)))?

**Comment by devapromix** [comment]
А ну тут все просто)) После боя есть некоторая вероятность заметить локацию-событие. И дальше только игрок решает, хочет ли он рискнуть. Выпасть может (из текущих событий, что уже реализованы) "обвал" (и, возможно, смерть), "ограбление" (часть золота игрока будет украдена), или "бесплатное исцеление" (лагерь алхимика). Будут и другие события. В будущем игрок сможет поймать вора и сразиться с ним.
