### ISSUE TITLE
Ошибка в инвентаре

### ISSUE THREAD

**Issue by devapromix** [devapromix/lizardry#90]
Почему-то не объединились 14 с 15:
![изображение](https://user-images.githubusercontent.com/40486018/200310472-40ab5920-5539-45d0-ac2d-bdbb669b8a1b.png)

_Originally posted by @LingamYoni in https://github.com/devapromix/lizardry/issues/89#issuecomment-1305539169_

**Comment by devapromix** [comment]
Вроде исправил этот баг.

**Comment by LingamYoni** [comment]
Сейчас проверю)

**Comment by devapromix** [comment]
Сработает с новым клиентом. Жди новой версии))
