### ISSUE TITLE
Не могу зарегистрироваться в текущем клиенте

### ISSUE THREAD

**Issue by phomm** [devapromix/lizardry#94]
Скачал клиента, распаковал, плюс прибил вопли винды, что угроза Trojan:Script/Wacatac.H!ml  (почитал на реддите, что это нередко false-positive у винды срабатывает )
пытался всячески зарегаться, ноль реакции в приложении.
открыл в дельфи, посмотрел под дебагом, на запрос который формирует программа, выдается пустая строка ответом (не ошибка и не джейсон а просто пустая). выдрал из дебага, пошёл подставил в постман, постман показывает, что ответ 200, но пустой.
смог только добиться ответа c ошибками типа 21/32 , стало быть, сервер то как-то работает.
Короче надо тебе, @devapromix , смотреть, что за дела.
Да и вообще ты давно уже что-то девайсы с телегой забросил :)

PS. @lingamyoni , с приездом из отпуска ) тоже заходяй , коль будет желание, так я распишу чего и как можно поиграть-потестить у меня

**Comment by LingamYoni** [comment]
> PS. @LingamYoni , с приездом из отпуска ) тоже заходяй , коль будет желание, так я распишу чего и как можно поиграть-потестить у меня

Ага, но по мне лучше б не возвращаться из отпуска вообще)) А куда заходить-то, напомни?

**Comment by devapromix** [comment]
Привет! Неожиданно конечно, гляну. Не часто глядел как регится, думал уж там все ок))

**Comment by devapromix** [comment]
Исправлено. Пока не обновлена версия Lizardry для теста нужно использовать мир Elvion.

**Comment by phomm** [comment]
@devapromix Спасибо! Проверю вечером
@LingamYoni У меня в гитхаб профиле есть контакты, при желании добавлю и в конфу в телеге. Также и доступы дам, покажу, расскажу.

**Comment by phomm** [comment]
Теперь в эльвионе такая ошибочка при попытке реги:
```
<br />
<b>Fatal error</b>: Uncaught Error: Class 'Player' not found in
/home/maxwof/domains/lizardry.pp.ua/public_html/elvion/includes/class.location.php:375
Stack trace:
#0 /home/maxwof/domains/lizardry.pp.ua/public_html/elvion/registration/registration.php(29):
Location::get_race_start_location('0')
#1 {main}
thrown in <b>/home/maxwof/domains/lizardry.pp.ua/public_html/elvion/includes/class.location.php</b> on line
<b>375</b><br />
```
это я из постмана взял при таком запросе :
`http://lizardry.pp.ua/elvion/registration/registration.php?action=registration&username=vlad&userpass=phph&charname=vlad&charrace=0&chargender=0`

**Comment by devapromix** [comment]
Пасиб. Гляну чего там)
